//! Golden-vector test for the `commit` module: `tests/golden/commit.json` per
//! VECTORS.md, generated by the Go implementation.

mod common;

use amber_store_core::commit::{Commit, Identity};
use amber_store_core::key::Key;

#[derive(serde::Deserialize)]
struct CommitFile {
    cases: Vec<Case>,
}

#[derive(serde::Deserialize)]
struct IdentityCase {
    name: String,
    email: String,
    /// Decimal i64 string (ns since the Unix epoch).
    when: String,
    tz_offset: i32,
}

#[derive(serde::Deserialize)]
struct Case {
    name: String,
    /// 64 lowercase hex chars.
    tree: String,
    parents: Vec<String>,
    author: IdentityCase,
    committer: IdentityCase,
    message: String,
    #[serde(default)]
    signature_hex: Option<String>,
    #[serde(default)]
    public_key_hex: Option<String>,
    /// The canonical encoding.
    bytes_hex: String,
    /// The commit's key: type 5, length = the encoding's byte length.
    key: String,
    /// The encoding without the signature field.
    signature_payload_hex: String,
}

fn key_of(h: &str, what: &str, i: usize) -> Key {
    let raw = hex::decode(h).unwrap_or_else(|e| panic!("case {i}: bad {what} hex: {e}"));
    Key::parse(&raw).unwrap_or_else(|e| panic!("case {i}: bad {what} key: {e}"))
}

fn opt_hex(field: &Option<String>, what: &str, i: usize) -> Vec<u8> {
    match field {
        Some(h) => hex::decode(h).unwrap_or_else(|e| panic!("case {i}: bad {what} hex: {e}")),
        None => Vec::new(),
    }
}

fn identity(c: &IdentityCase) -> Identity {
    Identity {
        name: c.name.clone(),
        email: c.email.clone(),
        when: common::parse_i64(&c.when),
        tz_offset: c.tz_offset,
    }
}

#[test]
fn golden_commit() {
    let Some(bytes) = common::load("commit.json") else {
        return;
    };
    let file: CommitFile = serde_json::from_slice(&bytes).expect("commit.json parses");
    assert!(!file.cases.is_empty(), "commit.json has no cases");

    for (i, c) in file.cases.iter().enumerate() {
        let commit = Commit {
            tree: key_of(&c.tree, "tree", i),
            parents: c.parents.iter().map(|p| key_of(p, "parent", i)).collect(),
            author: identity(&c.author),
            committer: identity(&c.committer),
            message: c.message.clone(),
            signature: opt_hex(&c.signature_hex, "signature", i),
            public_key: opt_hex(&c.public_key_hex, "public key", i),
        };

        // Encode and key must byte-match the Go implementation.
        let (key, enc) = commit
            .object()
            .unwrap_or_else(|e| panic!("case {i} ({:?}): encode: {e}", c.name));
        assert_eq!(
            hex::encode(&enc),
            c.bytes_hex,
            "case {i} ({:?}): encoding differs",
            c.name
        );
        assert_eq!(
            key.to_string(),
            c.key,
            "case {i} ({:?}): key differs",
            c.name
        );
        assert_eq!(
            hex::encode(commit.signature_payload().unwrap()),
            c.signature_payload_hex,
            "case {i} ({:?}): signature payload differs",
            c.name
        );

        // Decode must accept the canonical bytes and recover every field.
        let want = hex::decode(&c.bytes_hex).unwrap();
        let dec = Commit::decode(&want)
            .unwrap_or_else(|e| panic!("case {i} ({:?}): decode: {e}", c.name));
        assert_eq!(
            dec, commit,
            "case {i} ({:?}): decoded fields differ",
            c.name
        );
    }
}
