//! Golden-vector test for the `commit` module: `tests/golden/commit.json` per
//! VECTORS.md, generated by the Go implementation.

mod common;

use amber_store_core::commit::{self, Commit, Identity};
use amber_store_core::fstree;
use amber_store_core::key::{Key, Type};

#[derive(serde::Deserialize)]
struct CommitFile {
    cases: Vec<Case>,
}

#[derive(serde::Deserialize)]
struct IdentityCase {
    name: String,
    email: String,
    /// Decimal i64 string (ns since the Unix epoch).
    when: String,
    tz_offset: i32,
}

#[derive(serde::Deserialize)]
struct Case {
    name: String,
    /// 64 lowercase hex chars.
    tree: String,
    parents: Vec<String>,
    author: IdentityCase,
    committer: IdentityCase,
    message: String,
    #[serde(default)]
    signature_hex: Option<String>,
    #[serde(default)]
    public_key_hex: Option<String>,
    #[serde(default)]
    change_id_hex: Option<String>,
    /// The terms of a conflicted tree after the first; absent when resolved.
    #[serde(default)]
    conflict_terms: Vec<String>,
    /// One label per term counting the tree; absent when none is labelled.
    #[serde(default)]
    conflict_labels: Vec<String>,
    /// The canonical encoding.
    bytes_hex: String,
    /// The commit's key: type 5, length = the footprint — the encoding's byte
    /// length plus the length fields of the tree and of every conflict term.
    key: String,
    /// The encoding without the signature field.
    signature_payload_hex: String,
}

fn key_of(h: &str, what: &str, i: usize) -> Key {
    let raw = hex::decode(h).unwrap_or_else(|e| panic!("case {i}: bad {what} hex: {e}"));
    Key::parse(&raw).unwrap_or_else(|e| panic!("case {i}: bad {what} key: {e}"))
}

fn opt_hex(field: &Option<String>, what: &str, i: usize) -> Vec<u8> {
    match field {
        Some(h) => hex::decode(h).unwrap_or_else(|e| panic!("case {i}: bad {what} hex: {e}")),
        None => Vec::new(),
    }
}

fn identity(c: &IdentityCase) -> Identity {
    Identity {
        name: c.name.clone(),
        email: c.email.clone(),
        when: common::parse_i64(&c.when),
        tz_offset: c.tz_offset,
    }
}

#[test]
fn golden_commit() {
    let Some(bytes) = common::load("commit.json") else {
        return;
    };
    let file: CommitFile = serde_json::from_slice(&bytes).expect("commit.json parses");
    assert!(!file.cases.is_empty(), "commit.json has no cases");

    for (i, c) in file.cases.iter().enumerate() {
        let commit = Commit {
            tree: key_of(&c.tree, "tree", i),
            parents: c.parents.iter().map(|p| key_of(p, "parent", i)).collect(),
            author: identity(&c.author),
            committer: identity(&c.committer),
            message: c.message.clone(),
            signature: opt_hex(&c.signature_hex, "signature", i),
            public_key: opt_hex(&c.public_key_hex, "public key", i),
            change_id: opt_hex(&c.change_id_hex, "change id", i),
            conflict_terms: c
                .conflict_terms
                .iter()
                .map(|t| key_of(t, "conflict term", i))
                .collect(),
            conflict_labels: c.conflict_labels.clone(),
        };

        // Encode and key must byte-match the Go implementation.
        let (key, enc) = commit
            .object()
            .unwrap_or_else(|e| panic!("case {i} ({:?}): encode: {e}", c.name));
        assert_eq!(
            hex::encode(&enc),
            c.bytes_hex,
            "case {i} ({:?}): encoding differs",
            c.name
        );
        assert_eq!(
            key.to_string(),
            c.key,
            "case {i} ({:?}): key differs",
            c.name
        );
        assert_eq!(
            hex::encode(commit.signature_payload().unwrap()),
            c.signature_payload_hex,
            "case {i} ({:?}): signature payload differs",
            c.name
        );

        // The key carries the footprint: own bytes plus every tree, never a
        // parent. The walks hold it to that, and list the trees, then the
        // parents, as the commit's children.
        assert_eq!(key.type_(), Type::Commit, "case {i} ({:?})", c.name);
        let trees_len: u64 = commit.trees().iter().map(Key::length).sum();
        assert_eq!(
            key.length(),
            enc.len() as u64 + trees_len,
            "case {i} ({:?}): length field is not the footprint",
            c.name
        );
        assert_eq!(
            commit::footprint(enc.len() as u64, &commit.trees()),
            Ok(key.length())
        );
        let mut children = commit.trees();
        children.extend(&commit.parents);
        assert_eq!(
            fstree::child_keys(key, &enc).unwrap(),
            children,
            "case {i} ({:?}): children",
            c.name
        );
        let old_rule = Key::new(Type::Commit, enc.len() as u64, &enc);
        assert!(
            fstree::child_keys(old_rule, &enc).is_err(),
            "case {i} ({:?}): a key of the own-bytes rule was accepted",
            c.name
        );

        // Decode must accept the canonical bytes and recover every field.
        let want = hex::decode(&c.bytes_hex).unwrap();
        let dec = Commit::decode(&want)
            .unwrap_or_else(|e| panic!("case {i} ({:?}): decode: {e}", c.name));
        assert_eq!(
            dec, commit,
            "case {i} ({:?}): decoded fields differ",
            c.name
        );
    }

    // The two vectors annotated in architecture/commits.md.
    for (name, key) in [
        (
            "merge",
            "50afd48693e2ae8418fb83d0459174df45ba5fdddef67376e74ac6893a5abbed",
        ),
        (
            "conflicted",
            "5201139f190aa234ad713392987671d47e7e3292a613c62e3d14a85d614b300b",
        ),
    ] {
        let c = file
            .cases
            .iter()
            .find(|c| c.name == name)
            .unwrap_or_else(|| panic!("commit.json has no case {name:?}"));
        assert_eq!(c.key, key, "the documented {name} vector");
    }
    assert!(
        file.cases.iter().any(|c| c.conflict_terms.len() == 254),
        "commit.json has no case with the maximum number of conflict terms"
    );
}
